name: CI
on: 
  pull_request:
    branches: [develop]


# 0) Checkout code locally
# 1) Install dependencies
# 2) Check code formatting with prettier
# 3) Run Automated tests
# 4) Upload code coverage as Artifact
# 5) Cache dependencies


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: use NodeJS
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run format:check
      - run: npm test -- --coverage
        env:
          CI: true